name: Testing CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**'
      - '!src/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**'
      - '!src/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22.x, 23.x]
        os: [macos-latest, ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
